# Generated by Django 4.2.6 on 2023-10-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='des',
            new_name='desc',
        ),
    ]
